version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: react-scripts
    versions:
    - 4.0.1
